# -*- coding: utf-8 -*-
"""Translate.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V_2-adTskoi82U5onoAkn8U4Fpl4xGl2

# SCRIPT for TRANSLATION

Scripts needs to work in the following steps:
1. Translate english values
2. Pair them with their keys
3. Save as a CSV in CSV folder (for all languages + english)
4. Save as a json in json folder (for all languages)
"""

!pip install deep-translator tqdm

from deep_translator import MyMemoryTranslator
from deep_translator import GoogleTranslator
import pandas as pd
from tqdm import tqdm

import os
from google.colab import drive
drive.mount('drive/')

os.chdir('drive/My Drive/language')

# list of languages supported by deep_translator with language code
GL= {
    'af': 'afrikaans',
    'sq': 'albanian',
    'am': 'amharic',
    'ar': 'arabic',
    'hy': 'armenian',
    'az': 'azerbaijani',
    'eu': 'basque',
    'be': 'belarusian',
    'bn': 'bengali',
    'bs': 'bosnian',
    'bg': 'bulgarian',
    'ca': 'catalan',
    'ceb': 'cebuano',
    'ny': 'chichewa',
    'zh-cn': 'chinese (simplified)',
    'zh-tw': 'chinese (traditional)',
    'co': 'corsican',
    'hr': 'croatian',
    'cs': 'czech',
    'da': 'danish',
    'nl': 'dutch',
    'en': 'english',
    'eo': 'esperanto',
    'et': 'estonian',
    'tl': 'filipino',
    'fi': 'finnish',
    'fr': 'french',
    'fy': 'frisian',
    'gl': 'galician',
    'ka': 'georgian',
    'de': 'german',
    'el': 'greek',
    'gu': 'gujarati',
    'ht': 'haitian creole',
    'ha': 'hausa',
    'haw': 'hawaiian',
    'iw': 'hebrew',
    'he': 'hebrew',
    'hi': 'hindi',
    'hmn': 'hmong',
    'hu': 'hungarian',
    'is': 'icelandic',
    'ig': 'igbo',
    'id': 'indonesian',
    'ga': 'irish',
    'it': 'italian',
    'ja': 'japanese',
    'jw': 'javanese',
    'kn': 'kannada',
    'kk': 'kazakh',
    'km': 'khmer',
    'ko': 'korean',
    'ku': 'kurdish (kurmanji)',
    'ky': 'kyrgyz',
    'lo': 'lao',
    'la': 'latin',
    'lv': 'latvian',
    'lt': 'lithuanian',
    'lb': 'luxembourgish',
    'mk': 'macedonian',
    'mg': 'malagasy',
    'ms': 'malay',
    'ml': 'malayalam',
    'mt': 'maltese',
    'mi': 'maori',
    'mr': 'marathi',
    'mn': 'mongolian',
    'my': 'myanmar (burmese)',
    'ne': 'nepali',
    'no': 'norwegian',
    'or': 'odia',
    'ps': 'pashto',
    'fa': 'farsi',
    'pl': 'polish',
    'pt': 'portuguese',
    'pa': 'punjabi',
    'ro': 'romanian',
    'ru': 'russian',
    'sm': 'samoan',
    'gd': 'scots gaelic',
    'sr': 'serbian',
    'st': 'sesotho',
    'sn': 'shona',
    'sd': 'sindhi',
    'si': 'sinhala',
    'sk': 'slovak',
    'sl': 'slovenian',
    'so': 'somali',
    'es': 'spanish',
    'su': 'sundanese',
    'sw': 'swahili',
    'sv': 'swedish',
    'tg': 'tajik',
    'ta': 'tamil',
    'te': 'telugu',
    'th': 'thai',
    'tr': 'turkish',
    'uk': 'ukrainian',
    'ur': 'urdu',
    'ug': 'uyghur',
    'uz': 'uzbek',
    'vi': 'vietnamese',
    'cy': 'welsh',
    'xh': 'xhosa',
    'yi': 'yiddish',
    'yo': 'yoruba',
    'zu': 'zulu',}

gl = {}
for k, v in GL.items():
  # saving language name as key with language code as value
  gl[v] = k

# Translates list to given format
def translateCsv(tx, item):
    tt = []
    if(item=='burmese'):
      item='myanmar (burmese)'

    for i in tqdm(range(len(tx)), desc=item):
        try:
            b = MyMemoryTranslator(source="en", target=gl[item]).translate(text=tx[i])
        except:
            try:
                b = GoogleTranslator(source='auto', target=gl[item]).translate(text=tx[i])
            except Exception as e:
                b = tx[i]
                print(e)
        tt.append(b)
    return tt

english = pd.read_json('translation.json', orient='index')
tx = english[0].to_numpy()

tx

languages = pd.read_csv('languages.csv', header=None)[0].to_numpy()

languages[1]

for item in languages[36:43]:
    tt = translateCsv(tx, item)
    frame = pd.DataFrame(tt)
    frame.index = english.index

    # save to excel
    frame.to_csv( f'{item}.csv', header=False)
    # save to json
    frame.transpose().to_json(f'{item}.json',
                              orient='records', lines=True,
                              force_ascii=False)

